print("------------------------------")
print("Bem-vindo(a) ao cálculo de IMC (Índice de Massa Corpórea)")
print("------------------------------")
kg = float(input("Informe o seu peso em Kg: "))
print("------------------------------")
altura = float(input("Informe a sua altura: "))
print("------------------------------")
resultado =  float(kg / (altura*altura))
print("O resultado do seu IMC é " , round(resultado, 2))
